### ISSUE TITLE
modulo listar contas com problemas

### ISSUE THREAD

**Issue by uwandera** [uwandera/python_backend_ai#3]
Traceback (most recent call last):
  File "c:\Users\TESTE ROSE\Desktop\PythonAIBackEnd\src\python_backend_ai\Desafio2\desafio2.py", line 178, in <module>
    main()
  File "c:\Users\TESTE ROSE\Desktop\PythonAIBackEnd\src\python_backend_ai\Desafio2\desafio2.py", line 169, in main
    listar_contas(contas)                                                     fio2\desafio2.py", line 178, in <module>
  File "c:\Users\TESTE ROSE\Desktop\PythonAIBackEnd\src\python_backend_ai\Desafio2\desafio2.py", line 110, in listar_contas                                 fio2\desafio2.py", line 169, in main
    Agência\t\t{conta['agencia']}
                ~~~~~^^^^^^^^^^^                                              fio2\desafio2.py", line 110, in listar_contas
KeyError: 'agencia'
PS C:\Users\TESTE ROSE\Desktop\PythonAIBackEnd\src\python_backend_ai\Desafio2>

**Comment by uwandera** [comment]
nome de variaveis agência e usuário estavam fora do padrão
